steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lovelace-presales-demo/books', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lovelace-presales-demo/books']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'books', '--image', 'gcr.io/lovelace-presales-demo/books','--allow-unauthenticated', '--region', 'us-east1']
images:
- gcr.io/lovelace-presales-demo/books