// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	Name      string  `json:"name"`
	YearBorn  int     `json:"yearBorn"`
	YearDied  *int    `json:"yearDied"`
	WhereBorn *string `json:"whereBorn"`
	Biography *string `json:"biography"`
}

func (Author) IsEntity() {}
