version: 2.0

jobs:
  run_client:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: pip install -r client/requirements.txt
      - run: python client/main.py

workflows:
  version: 2
  workweek:
    triggers:
      - schedule:
          cron: "* 11-18 * * 1-5"
          filters:
            branches:
              only: master
    jobs:
      - run_client