push:
	apollo service:push \
	--localSchemaFile=rickand.graphqls \
	--graph=jesse-test-1xc6kq \
	--variant=current \
	--serviceName=rickandmorty \
	--serviceURL=https://rickandmortyapi.com/graphql

push2:
	apollo service:push \
	--localSchemaFile=hasura.graphqls \
	--graph=jesse-test-1xc6kq \
	--variant=current \
	--serviceName=hasura \
	--serviceURL=https://wealthy-dragon-32.hasura.app/v1/graphql
