runtime: go115
service: authors
automatic_scaling:
  target_cpu_utilization: 0.90
  min_instances: 0
  max_instances: 2
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 200